source ./folders/functions.sh
dir="_CPS2"
out=$1
horizontal=$2
vertical=$3

setout "$out"
sethorizontal "$horizontal"
setvertical "$vertical"

add "$dir" "V" "19XX The War Against Destiny (Euro 960104).mra" "_19XX The War Against Destiny"
add "$dir" "V" "Dimahoo (Euro 000121).mra" "_Dimahoo"
add "$dir" "H" "1944 The Loop Master (Euro 000620).mra" "_1944 The Loop Master"
add "$dir" "H" "Adventure Quiz Capcom World 2 (Japan 920611).mra" "_Adventure Quiz Capcom World 2"
add "$dir" "H" "Alien vs. Predator (Euro 940520).mra" "_Alien vs. Predator"
add "$dir" "H" "Armored Warriors (Euro 941024).mra" "_Armored Warriors"
add "$dir" "H" "Battle Circuit (Euro 970319).mra" "_Battle Circuit"
add "$dir" "H" "Capcom Sports Club (Euro 971017).mra" "_Capcom Sports Club"
add "$dir" "H" "Cyberbots Fullmetal Madness (Euro 950424).mra" "_Cyberbots Fullmetal Madness"
add "$dir" "H" "Darkstalkers The Night Warriors (Euro 940705).mra" "_Darkstalkers The Night Warriors"
add "$dir" "H" "Dungeons & Dragons Shadow over Mystara (Euro 960619).mra" "_Dungeons & Dragons Shadow over Mystara"
add "$dir" "H" "Dungeons & Dragons Tower of Doom (Euro 940412).mra" "_Dungeons & Dragons Tower of Doom"
add "$dir" "H" "Eco Fighters (World 931203).mra" "_Eco Fighters"
add "$dir" "H" "Giga Wing (USA 990222).mra" "_Giga Wing"
add "$dir" "H" "Hyper Street Fighter II The Anniversary Edition (USA 040202).mra" "_Hyper Street Fighter II The Anniversary Edition"
add "$dir" "H" "Janpai Puzzle Choukou (Japan 010820).mra" "_Janpai Puzzle Choukou"
add "$dir" "H" "Jyangokushi Haoh no Saihai (Japan 990527).mra" "_Jyangokushi Haoh no Saihai"
add "$dir" "H" "Mars Matrix Hyper Solid Shooting (USA 000412).mra" "_Mars Matrix Hyper Solid Shooting"
add "$dir" "H" "Marvel Super Heroes (Euro 951024).mra" "_Marvel Super Heroes"
add "$dir" "H" "Marvel Super Heroes Vs. Street Fighter (Euro 970625).mra" "_Marvel Super Heroes Vs. Street Fighter"
add "$dir" "H" "Marvel Vs. Capcom Clash of Super Heroes (Euro 980123).mra" "_Marvel Vs. Capcom Clash of Super Heroes"
add "$dir" "H" "Mega Man 2 The Power Fighters (USA 960708).mra" "_Mega Man 2 The Power Fighters"
add "$dir" "H" "Mighty! Pang (Euro 001010).mra" "_Mighty! Pang"
add "$dir" "H" "Night Warriors Darkstalkers' Revenge (Euro 950316).mra" "_Night Warriors Darkstalkers' Revenge"
add "$dir" "H" "Pnickies (Japan 940608).mra" "_Pnickies"
add "$dir" "H" "Progear (USA 010117).mra" "_Progear"
add "$dir" "H" "Puzz Loop 2 (Euro 010302).mra" "_Puzz Loop 2"
add "$dir" "H" "Quiz Nanairo Dreams Nijiirochou no Kiseki (Japan 96086).mra" "_Quiz Nanairo Dreams Nijiirochou no Kiseki"
add "$dir" "H" "Ring of Destruction Slammasters II (Euro 940902).mra" "_Ring of Destruction Slam Masters II"
add "$dir" "H" "Street Fighter Alpha 2 (Euro 960229).mra" "_Street Fighter Alpha 2"
add "$dir" "H" "Street Fighter Alpha 3 (Euro 980904).mra" "_Street Fighter Alpha 3"
add "$dir" "H" "Street Fighter Zero 3 Challenger's Edition (USA 980904).mra" "_Street Fighter Alpha 3"
add "$dir" "H" "Street Fighter Alpha 3 Challenger's Edition (USA 980904).mra" "_Street Fighter Alpha 3"
add "$dir" "H" "Street Fighter Zero (CPS Changer, Japan 951020).mra" "_Street Fighter Alpha Warriors' Dreams"
add "$dir" "H" "Street Fighter Zero 2 Alpha (Asia 960826).mra" "_Street Fighter Zero 2 Alpha"
add "$dir" "H" "Super Gem Fighter Mini Mix (USA 970904).mra" "_Super Gem Fighter Mini Mix"
add "$dir" "H" "Super Puzzle Fighter II Turbo (Euro 960529).mra" "_Super Puzzle Fighter II Turbo"
add "$dir" "H" "Super Street Fighter II The New Challengers (World 931005).mra" "_Super Street Fighter II The New Challengers"
add "$dir" "H" "Super Street Fighter II Turbo (World 940223).mra" "_Super Street Fighter II Turbo"
add "$dir" "H" "Vampire Hunter 2 Darkstalkers Revenge (Japan 970929).mra" "_Vampire Hunter 2 Darkstalkers Revenge"
add "$dir" "H" "Vampire Savior 2 The Lord of Vampire (Japan 970913).mra" "_Vampire Savior 2 The Lord of Vampire"
add "$dir" "H" "Vampire Savior The Lord of Vampire (Euro 970519).mra" "_Vampire Savior The Lord of Vampire"
add "$dir" "H" "X-Men Children of the Atom (Euro 950331).mra" "_X-Men Children of the Atom"
add "$dir" "H" "X-Men Vs. Street Fighter (Euro 961004).mra" "_X-Men Vs. Street Fighter"
add "$dir" "H" "Final Fight AE CPS2 Patch.mra" "_Final Fight AE"
dot