#!/bin/bash  
source ./folders/functions.sh

dir="_Konami"
out=$1
horizontal=$2
vertical=$3

setout "$out"
sethorizontal "$horizontal"
setvertical "$vertical"

add "$dir" "V" "Amidar (Scramble).mra" "_Amidar"
add "$dir" "V" "Fast Lane.mra" "_Fast Lane"
add "$dir" "V" "Finalizer - Super Transformation (Set 1).mra" "_Finalizer - Super Transformation"
add "$dir" "V" "Finalizer - Super Transformation (Set 2) [bl].mra" "_Finalizer - Super Transformation"
add "$dir" "V" "Finalizer - Super Transformation (Set 2).mra" "_Finalizer - Super Transformation"
add "$dir" "V" "Frogger (Konami Bugfixed).mra" "_Frogger"
add "$dir" "V" "Frogger (Sega, Set 2).mra" "_Frogger"
add "$dir" "V" "Gyruss.mra" "_Gyruss"
add "$dir" "V" "Jackal (W) [bl].mra" "_Jackal"
add "$dir" "V" "Jackal (W).mra" "_Jackal"
add "$dir" "V" "Jackal (W, Rotary).mra" "_Jackal"
add "$dir" "V" "Kicker.mra" "_Kicker"
add "$dir" "V" "Mikie.mra" "_Mikie"
add "$dir" "V" "MX5000.mra" "_MX5000"
add "$dir" "V" "Pooyan.mra" "_Pooyan"
add "$dir" "V" "Road Fighter (set 1).mra" "_Road Fighter"
add "$dir" "V" "Roc'n Rope.mra" "_Roc'n Rope"
add "$dir" "V" "Scooter Shooter.mra" "_Scooter Shooter"
add "$dir" "V" "Scramble (Stern, Set 1).mra" "_Scramble"
add "$dir" "V" "Super Basketball (version I, encrypted).mra" "_Super Basketball"
add "$dir" "V" "Super Cobra.mra" "_Super Cobra"
add "$dir" "V" "The End (bkg).mra" "_The End"
add "$dir" "V" "The End.mra" "_The End"
add "$dir" "V" "Time Pilot '84 (Set 1).mra" "_Time Pilot 84"
add "$dir" "V" "Time Pilot '84 (Set 2).mra" "_Time Pilot 84"
add "$dir" "V" "Time Pilot '84 (Set 3).mra" "_Time Pilot 84"
add "$dir" "V" "Time Pilot.mra" "_Time Pilot"
add "$dir" "V" "Tokushu Butai Jackal (JP).mra" "_Jackal"
add "$dir" "V" "Top Gunner (US) [bl].mra" "_Jackal"
add "$dir" "V" "Top Gunner (US).mra" "_Jackal"
add "$dir" "V" "Trick Trap (World).mra" "_Labyrinth Runner"
add "$dir" "V" "Super Contra (set 1).mra" "_Super Contra"

add "$dir" "H" "Aliens (World set 1).mra" "_Aliens"
add "$dir" "H" "Combat School (joystick).mra" "_Combat School"
add "$dir" "H" "Crime Fighters (World 2 players).mra" "_Crime Fighters"
add "$dir" "H" "Green Beret.mra" "_Green Beret"
add "$dir" "H" "Haunted Castle (version M).mra" "_Haunted Castle"
add "$dir" "H" "Hyper Sports.mra" "_Hyper Sports"
add "$dir" "H" "Iron Horse (Ver. K).mra" "_Iron Horse"
add "$dir" "H" "Jailbreak.mra" "_JailBreak"
add "$dir" "H" "Konami's Ping-Pong.mra" "_Konami's Ping-Pong"
add "$dir" "H" "M.I.A. - Missing in Action (version T).mra" "_M.I.A. - Missing in Action"
add "$dir" "H" "Manhattan 24 Bunsyo (J).mra" "_JailBreak"
add "$dir" "H" "Mr. Goemon.mra" "_Mr. Goemon"
add "$dir" "H" "Nemesis (ROM Version).mra" "_Nemesis"
add "$dir" "H" "River Patrol (JP, Unprotected).mra" "_River Patrol"
add "$dir" "H" "Rush'n Attack (US).mra" "_Green Beret"
add "$dir" "H" "Teenage Mutant Ninja Turtles (World 4 Players, version X).mra" "_Teenage Mutant Ninja Turtles"
add "$dir" "H" "The Simpsons (4 Players World, set 1).mra" "_The Simpsons"
add "$dir" "H" "Track & Field.mra" "_Track & Field"
add "$dir" "H" "Yie Ar Kung-Fu (program code I).mra" "_Yie Ar Kung-Fu"
dot