#!/bin/bash
source ./folders/functions.sh
loadsetup

res=$(exist "Metal Slug - Super Vehicle-001.mra")
if [ "$res" == "1" ]; then
   dir="_Neo-geo"
   outdir=$1

   #add "$dir" "H" "Columns.mra" 
   #add "$dir" "H" "Frog Feast.mra" 
   #add "$dir" "H" "NeoTRIS (free beta version).mra" 
   #add "$dir" "H" "Quiz Daisousa Sen - The Last Count Down.mra" 
   #add "$dir" "H" "Tetris.mra" 
   #add "$dir" "H" "NeoTRIS (free beta version).mra" 
   #add "$dir" "H"  "Neo Fight.mra" 
   #add "$dir" "H"  "Neo Thunder.mra" 

   add "$dir" "H"  "#neogeo.mgl" 
   add "$dir" "H"  "2020 Super Baseball.mra" "" "" "SPO"
   add "$dir" "H"  "3 Count Bout.mra" "" "" "SPO"
   add "$dir" "H"  "Aero Fighters 2.mra" "" "" "STG"
   add "$dir" "H"  "Aero Fighters 3.mra" "" "" "STG"
   add "$dir" "H"  "Aggressors of Dark Kombat.mra" "" "" "VSF"
   add "$dir" "H"  "Alpha Mission II.mra" "" "" "STG"
   add "$dir" "H"  "Andro Dunos.mra" "" "" "STG"
   add "$dir" "H"  "Art of Fighting.mra" "" "" "VSF"
   add "$dir" "H"  "Art of Fighting 2.mra" "" "" "VSF"
   add "$dir" "H"  "Art of Fighting 3 - The Path of the Warrior.mra" "" "" "VSF"
   add "$dir" "H"  "Bakatonosama Mahjong Manyuuki.mra"  
   add "$dir" "H"  "Bang Bang Busters (2010 NCI release).mra" "_Bang Bang Busters" "" "ACT"
   add "$dir" "H"  "Bang Bang Busters.mra" "_Bang Bang Busters" "" "ACT"
   add "$dir" "H"  "Bang Bead.mra" "" "" "SPO"
   add "$dir" "H"  "Baseball Stars 2.mra" "" "" "SPO"
   add "$dir" "H"  "Baseball Stars Professional.mra" "" "" "SPO"
   add "$dir" "H"  "Battle Flip Shot.mra" "" "" "SPO"
   add "$dir" "H"  "Blazing Star.mra" "" "" "STG"
   add "$dir" "H"  "Blue's Journey.mra" "" "" "ACT"
   add "$dir" "H"  "Breakers.mra" "" "" "VSF"
   add "$dir" "H"  "Breakers Revenge.mra" "" "" "VSF"
   add "$dir" "H"  "Burning Fight.mra" "" "" "BEA"
   add "$dir" "H"  "Cabal.mra" "" "" "ACT"
   add "$dir" "H"  "Captain Tomaday.mra" "" "" "STG"
   add "$dir" "H"  "Choutetsu Brikin'ger.mra"
   add "$dir" "H"  "Crossed Swords.mra" "" "" "ACT"
   add "$dir" "H"  "Crossed Swords 2.mra" "" "" "ACT"
   add "$dir" "H"  "Cyber-Lip.mra" "" "" "ACT"
   add "$dir" "H"  "Digger Man (prototype).mra" "" "" "PUZ"
   add "$dir" "H"  "Double Dragon neo.mra" "" "" "VSF"
   add "$dir" "H"  "Dragon's Heaven (development board).mra" 
   add "$dir" "H"  "Eight Man.mra" "" "" "BEA"
   add "$dir" "H"  "Far East of Eden - Kabuki Klash.mra" "" "" "VSF"
   add "$dir" "H"  "Fatal Fury - King of Fighters.mra" "" "" "VSF"
   add "$dir" "H"  "Fatal Fury 2.mra" "" "" "VSF"
   add "$dir" "H"  "Fatal Fury 3 - Road to the Final Victory (alternate set).mra" "" "" "VSF"
   add "$dir" "H"  "Fatal Fury Special.mra" "" "" "VSF"
   add "$dir" "H"  "Fight Fever.mra" "" "" "VSF"
   add "$dir" "H"  "Football Frenzy.mra" "" "" "SPO"
   add "$dir" "H"  "Galaxy Fight - Universal Warriors.mra" "" "" "VSF"
   add "$dir" "H"  "Ganryu.mra" "" "" "BEA"
   add "$dir" "H"  "Garou - Mark of the Wolves.mra" "" "" "VSF"
   add "$dir" "H"  "Ghost Pilots.mra" "" "" "STG"
   add "$dir" "H"  "Ghostlop.mra" "" "" "PUZ"
   add "$dir" "H"  "Goal! Goal! Goal!.mra" "" "" "SPO"
   add "$dir" "H"  "Gururin.mra" "" "" "PUZ"
   add "$dir" "H"  "Idol Mahjong Final Romance 2.mra" 
   add "$dir" "H"  "Ironclad.mra" "" "" "STG"
   add "$dir" "H"  "Janshin Densetsu - Quest of Jongmaster.mra" 
   add "$dir" "H"  "Karnov's Revenge.mra" "" "" "VSF"
   add "$dir" "H"  "King of the Monsters.mra" "" "" "BEA"
   add "$dir" "H"  "King of the Monsters 2 - The Next Thing.mra" "" "" "BEA"
   add "$dir" "H"  "Kizuna Encounter - Super Tag Battle.mra" "" "" "VSF"
   add "$dir" "H"  "Last Hope.mra" "" "" "STG"
   add "$dir" "H"  "Last Resort.mra" "" "" "STG"
   add "$dir" "H"  "League Bowling.mra" "" "" "SPO"
   add "$dir" "H"  "Legend of Success Joe.mra" "" "" "BEA"
   add "$dir" "H"  "Magical Drop II.mra" "" "" "PUZ"
   add "$dir" "H"  "Magical Drop III.mra" "" "" "PUZ"
   add "$dir" "H"  "Magician Lord.mra" "" "" "ACT"
   add "$dir" "H"  "Mahjong Kyo Retsuden.mra" 
   add "$dir" "H"  "Matrimelee.mra" "" "" "VSF"
   add "$dir" "H"  "Metal Slug - Super Vehicle-001.mra" "" "" "RNG"
   add "$dir" "H"  "Metal Slug 2 - Super Vehicle-001-II.mra" "_Metal Slug 2 - Super Vehicle-001-II" "" "RNG"
   add "$dir" "H"  "Metal Slug 2 Turbo.mra" "_Metal Slug 2 - Super Vehicle-001-II" "" "RNG"
   add "$dir" "H"  "Metal Slug 3.mra" "" "" "RNG"
   add "$dir" "H"  "Metal Slug 4.mra" "" "" "RNG"
   add "$dir" "H"  "Metal Slug 5.mra" "" "" "RNG"
   add "$dir" "H"  "Metal Slug X - Super Vehicle-001.mra" "" "" "RNG"
   add "$dir" "H"  "Minasan no Okagesamadesu! Dai Sugoroku Taikai.mra" 
   add "$dir" "H"  "Money Puzzle Exchanger.mra" "" "" "PUZ"
   add "$dir" "H"  "Mutation Nation.mra" "" "" "BEA"
   add "$dir" "H"  "NAM-1975.mra" "" "" "ACT"
   add "$dir" "H"  "Neo Bomberman.mra" "" "" "ACT"
   add "$dir" "H"  "Neo Drift Out - New Technology.mra" "" "" "SPO"
   add "$dir" "H"  "Neo Mr. Do!.mra" "" "" "PUZ"
   add "$dir" "H"  "Neo Turf Masters.mra" "" "" "SPO"
   add "$dir" "H"  "Neo-Geo Cup '98 - The Road to the Victory.mra" "" "" "SPO"
   add "$dir" "H"  "Nightmare in the Dark.mra" "" "" "ACT"
   add "$dir" "H"  "Ninja Combat.mra" "" "" "ACT"
   add "$dir" "H"  "Ninja Commando.mra" "" "" "STG"
   add "$dir" "H"  "Ninja Master's - Haoh-ninpo-cho.mra" "" "" "VSF"
   add "$dir" "H"  "OverTop.mra" "" "" "SPO"
   add "$dir" "H"  "Pae Wang Jeon Seol.mra" "" "" "VSF"
   add "$dir" "H"  "Panic Bomber.mra" "" "" "ACT"
   add "$dir" "H"  "Pleasure Goal.mra" "" "" "SPO"
   add "$dir" "H"  "Pochi and Nyaa.mra" "" "" "PUZ"
   add "$dir" "H"  "Pop 'n Bounce.mra" "" "" "PUZ"
   add "$dir" "H"  "Power Spikes II.mra" "" "" "SPO"
   add "$dir" "H"  "Prehistoric Isle 2.mra" "" "" "STG"
   add "$dir" "H"  "Pulstar.mra" "" "" "STG"
   add "$dir" "H"  "Puzzle Bobble.mra"  "" "" "PUZ"
   add "$dir" "H"  "Puzzle Bobble 2.mra" ""  "" "PUZ"
   add "$dir" "H"  "Puzzle De Pon!.mra" "" "" "PUZ"
   add "$dir" "H"  "Puzzle De Pon! R!.mra" "" "" "PUZ"
   add "$dir" "H"  "Puzzled.mra" "" "" "PUZ"
   add "$dir" "H"  "Quiz Daisousa Sen - The Last Count Down.mra" 
   add "$dir" "H"  "Quiz King of Fighters.mra" 
   add "$dir" "H"  "Quiz Meitantei Neo & Geo - Quiz Daisousa Sen part 2.mra" 
   add "$dir" "H"  "Rage of the Dragons.mra" "" "" "VSF"
   add "$dir" "H"  "Ragnagard.mra" "" "" "VSF"
   add "$dir" "H"  "Real Bout Fatal Fury (bug fix revision).mra" "" "" "VSF"
   add "$dir" "H"  "Real Bout Fatal Fury 2 - The Newcomers.mra" "" "" "VSF"
   add "$dir" "H"  "Real Bout Fatal Fury Special.mra" "" "" "VSF"
   add "$dir" "H"  "Riding Hero.mra" "" "" "SPO"
   add "$dir" "H"  "Robo Army.mra" "" "" "BEA"
   add "$dir" "H"  "Samurai Shodown.mra" "" "" "VSF"
   add "$dir" "H"  "Samurai Shodown II.mra" "" "" "VSF"
   add "$dir" "H"  "Samurai Shodown III.mra" "" "" "VSF"
   add "$dir" "H"  "Samurai Shodown IV - Amakusa's Revenge.mra" "" "" "VSF"
   add "$dir" "H"  "Samurai Shodown V.mra" "" "" "VSF"
   add "$dir" "H"  "Samurai Shodown V Perfect.mra" "" "" "VSF"
   add "$dir" "H"  "Samurai Shodown V Special.mra" "" "" "VSF"
   add "$dir" "H"  "Savage Reign.mra" "" "" "VSF"
   add "$dir" "H"  "Sengoku.mra" "" "" "BEA"
   add "$dir" "H"  "Sengoku 2.mra" "" "" "BEA"
   add "$dir" "H"  "Sengoku 3.mra" "" "" "BEA"
   add "$dir" "H"  "Shock Troopers.mra" "" "" "STG"
   add "$dir" "H"  "Shock Troopers - 2nd Squad.mra" "" "" "STG"
   add "$dir" "H"  "Shougi no Tatsujin - Master of Shougi.mra"
   add "$dir" "H"  "SNK vs. Capcom - SVC Chaos.mra" "" "" "VSF"
   add "$dir" "H"  "Soccer Brawl.mra" "" "" "SPO"
   add "$dir" "H"  "Spin Master.mra" "" "" "ACT"
   add "$dir" "H"  "Stakes Winner.mra" "" "" "SPO"
   add "$dir" "H"  "Stakes Winner 2.mra" "" "" "SPO"
   add "$dir" "H"  "Street Hoop.mra" "" "" "SPO"
   add "$dir" "H"  "Strikers 1945 Plus.mra" "" "" "STG"
   add "$dir" "H"  "Super Bubble Pop.mra" "" ""  "PUZ"
   add "$dir" "H"  "Super Dodge Ball.mra" "" "" "SPO"
   add "$dir" "H"  "Super Sidekicks.mra" "" "" "SPO"
   add "$dir" "H"  "Super Sidekicks 2 - The World Championship.mra" "" "" "SPO"
   add "$dir" "H"  "Super Sidekicks 3 - The Next Glory.mra" "" "" "SPO"
   add "$dir" "H"  "Tecmo World Soccer '96.mra" "" "" "SPO"
   add "$dir" "H"  "The Eye of Typhoon - Tsunami Edition.mra" 
   add "$dir" "H"  "The Irritating Maze.mra" 
   add "$dir" "H"  "The King of Fighters '94.mra" "" "" "VSF"
   add "$dir" "H"  "The King of Fighters '95.mra" "" "" "VSF"
   add "$dir" "H"  "The King of Fighters '96.mra" "" "" "VSF"
   add "$dir" "H"  "The King of Fighters '97.mra" "" "" "VSF"
   add "$dir" "H"  "The King of Fighters '98 - The Slugfest.mra" "" "" "VSF"
   add "$dir" "H"  "The King of Fighters '99 - Millennium Battle.mra" "" "" "VSF"
   add "$dir" "H"  "The King of Fighters 2000.mra" "" "" "VSF"
   add "$dir" "H"  "The King of Fighters 2001.mra" "" "" "VSF"
   add "$dir" "H"  "The King of Fighters 2002.mra" "" "" "VSF"
   add "$dir" "H"  "The King of Fighters 2003.mra" "" "" "VSF"
   add "$dir" "H"  "The Last Blade.mra" "" "" "" "VSF"
   add "$dir" "H"  "The Last Blade 2.mra" "" "" "VSF"
   add "$dir" "H"  "The Super Spy.mra" "" "" "ACT"
   add "$dir" "H"  "The Ultimate 11 - The SNK Football Championship.mra" "" "" "SPO"
   add "$dir" "H"  "Thrash Rally.mra" "" "" "SPO"
   add "$dir" "H"  "Top Hunter - Roddy & Cathy.mra" "" "" "ACT"
   add "$dir" "H"  "Top Player's Golf.mra" "" "" "SPO"
   add "$dir" "H"  "Treasure of the Caribbean.mra" "" "" "PUZ"
   add "$dir" "H"  "Twinkle Star Sprites.mra" "" "" "STG"
   add "$dir" "H"  "Viewpoint.mra" "" "" "STG"
   add "$dir" "H"  "Voltage Fighter - Gowcaizer.mra" "" "" "VSF"
   add "$dir" "H"  "Waku Waku 7.mra" "" "" "VSF"
   add "$dir" "H"  "Windjammers.mra" "" "" "SPO"
   add "$dir" "H"  "World Heroes.mra" "" "" "VSF"
   add "$dir" "H"  "World Heroes 2.mra" "" "" "VSF"
   add "$dir" "H"  "World Heroes 2 Jet.mra" "" "" "VSF"
   add "$dir" "H"  "World Heroes Perfect.mra" "" "" "VSF"
   add "$dir" "H"  "Xeno Crisis.mra" "" "" "ACT"
   add "$dir" "H"  "Zed Blade.mra" "" "" "STG"
   add "$dir" "H"  "Zintrick.mra" "" "" "PUZ"
   add "$dir" "H"  "Zupapa!.mra" "" "" "ACT"
   dot
fi
