source ./folders/functions.sh

dir="_Neo-geo"
outdir=$1
horizontal=$2
vertical=$3
stg_horizontal=$4
stg_vertical=$5

#add "$dir" "H" "Columns.mra" 
#add "$dir" "H" "Frog Feast.mra" 
#add "$dir" "H" "NeoTRIS (free beta version).mra" 
#add "$dir" "H" "Quiz Daisousa Sen - The Last Count Down.mra" 
#add "$dir" "H" "Tetris.mra" 
#add "$dir" "H" "NeoTRIS (free beta version).mra" 

add "$dir" "H"  "#neogeo.mgl" 
add "$dir" "H"  "2020 Super Baseball.mra" 
add "$dir" "H"  "3 Count Bout.mra" 
add "$dir" "H"  "Aero Fighters 2.mra" 
add "$dir" "H"  "Aero Fighters 3.mra" 
add "$dir" "H"  "Aggressors of Dark Kombat.mra" 
add "$dir" "H"  "Alpha Mission II.mra" 
add "$dir" "H"  "Andro Dunos.mra" 
add "$dir" "H"  "Art of Fighting.mra" 
add "$dir" "H"  "Art of Fighting 2.mra" 
add "$dir" "H"  "Art of Fighting 3 - The Path of the Warrior.mra" 
add "$dir" "H"  "Bakatonosama Mahjong Manyuuki.mra" 
add "$dir" "H"  "Bang Bang Busters (2010 NCI release).mra" "_Bang Bang Busters"
add "$dir" "H"  "Bang Bang Busters.mra" "_Bang Bang Busters"
add "$dir" "H"  "Bang Bead.mra" 
add "$dir" "H"  "Baseball Stars 2.mra" 
add "$dir" "H"  "Baseball Stars Professional.mra" 
add "$dir" "H"  "Battle Flip Shot.mra" 
add "$dir" "H"  "Blazing Star.mra" 
add "$dir" "H"  "Blue's Journey.mra" 
add "$dir" "H"  "Breakers.mra" 
add "$dir" "H"  "Breakers Revenge.mra" 
add "$dir" "H"  "Burning Fight.mra" 
add "$dir" "H"  "Cabal.mra" 
add "$dir" "H"  "Captain Tomaday.mra" 
add "$dir" "H"  "Choutetsu Brikin'ger.mra" 
add "$dir" "H"  "Crossed Swords.mra" 
add "$dir" "H"  "Crossed Swords 2.mra" 
add "$dir" "H"  "Cyber-Lip.mra" 
add "$dir" "H"  "Digger Man (prototype).mra" 
add "$dir" "H"  "Double Dragon neo.mra" 
add "$dir" "H"  "Dragon's Heaven (development board).mra" 
add "$dir" "H"  "Eight Man.mra" 
add "$dir" "H"  "Far East of Eden - Kabuki Klash.mra" 
add "$dir" "H"  "Fatal Fury - King of Fighters.mra" 
add "$dir" "H"  "Fatal Fury 2.mra" 
add "$dir" "H"  "Fatal Fury 3 - Road to the Final Victory (alternate set).mra" 
add "$dir" "H"  "Fatal Fury Special.mra" 
add "$dir" "H"  "Fight Fever.mra" 
add "$dir" "H"  "Football Frenzy.mra" 
add "$dir" "H"  "Galaxy Fight - Universal Warriors.mra" 
add "$dir" "H"  "Ganryu.mra" 
add "$dir" "H"  "Garou - Mark of the Wolves.mra" 
add "$dir" "H"  "Ghost Pilots.mra" 
add "$dir" "H"  "Ghostlop.mra" 
add "$dir" "H"  "Goal! Goal! Goal!.mra" 
add "$dir" "H"  "Gururin.mra" 
add "$dir" "H"  "Idol Mahjong Final Romance 2.mra" 
add "$dir" "H"  "Ironclad.mra" 
add "$dir" "H"  "Janshin Densetsu - Quest of Jongmaster.mra" 
add "$dir" "H"  "Karnov's Revenge.mra" 
add "$dir" "H"  "King of the Monsters.mra" 
add "$dir" "H"  "King of the Monsters 2 - The Next Thing.mra" 
add "$dir" "H"  "Kizuna Encounter - Super Tag Battle.mra" 
add "$dir" "H"  "Last Hope.mra" 
add "$dir" "H"  "Last Resort.mra" 
add "$dir" "H"  "League Bowling.mra" 
add "$dir" "H"  "Legend of Success Joe.mra" 
add "$dir" "H"  "Magical Drop II.mra" 
add "$dir" "H"  "Magical Drop III.mra" 
add "$dir" "H"  "Magician Lord.mra" 
add "$dir" "H"  "Mahjong Kyo Retsuden.mra" 
add "$dir" "H"  "Matrimelee.mra" 
add "$dir" "H"  "Metal Slug - Super Vehicle-001.mra" 
add "$dir" "H"  "Metal Slug 2 - Super Vehicle-001-II.mra" "_Metal Slug 2 - Super Vehicle-001-II"
add "$dir" "H"  "Metal Slug 2 Turbo.mra" "_Metal Slug 2 - Super Vehicle-001-II"
add "$dir" "H"  "Metal Slug 3.mra" 
add "$dir" "H"  "Metal Slug 4.mra" 
add "$dir" "H"  "Metal Slug 5.mra" 
add "$dir" "H"  "Metal Slug X - Super Vehicle-001.mra" 
add "$dir" "H"  "Minasan no Okagesamadesu! Dai Sugoroku Taikai.mra" 
add "$dir" "H"  "Money Puzzle Exchanger.mra" 
add "$dir" "H"  "Mutation Nation.mra" 
add "$dir" "H"  "NAM-1975.mra" 
add "$dir" "H"  "Neo Bomberman.mra" 
add "$dir" "H"  "Neo Drift Out - New Technology.mra" 
add "$dir" "H"  "Neo Fight.mra" 
add "$dir" "H"  "Neo Mr. Do!.mra" 
add "$dir" "H"  "Neo Thunder.mra" 
add "$dir" "H"  "Neo Turf Masters.mra" 
add "$dir" "H"  "Neo-Geo Cup '98 - The Road to the Victory.mra" 
add "$dir" "H"  "Nightmare in the Dark.mra" 
add "$dir" "H"  "Ninja Combat.mra" 
add "$dir" "H"  "Ninja Commando.mra" 
add "$dir" "H"  "Ninja Master's - Haoh-ninpo-cho.mra" 
add "$dir" "H"  "OverTop.mra" 
add "$dir" "H"  "Pae Wang Jeon Seol.mra" 
add "$dir" "H"  "Panic Bomber.mra" 
add "$dir" "H"  "Pleasure Goal.mra" 
add "$dir" "H"  "Pochi and Nyaa.mra" 
add "$dir" "H"  "Pop 'n Bounce.mra" 
add "$dir" "H"  "Power Spikes II.mra" 
add "$dir" "H"  "Prehistoric Isle 2.mra" 	
add "$dir" "H"  "Pulstar.mra" 
add "$dir" "H"  "Puzzle Bobble.mra" "" "" "PUZ"
add "$dir" "H"  "Puzzle Bobble 2.mra" "" "" "PUZ"
add "$dir" "H"  "Puzzle De Pon!.mra" "" "" "PUZ"
add "$dir" "H"  "Puzzle De Pon! R!.mra" "" "" "PUZ"
add "$dir" "H"  "Puzzled.mra" "" "" "PUZ"
add "$dir" "H"  "Quiz Daisousa Sen - The Last Count Down.mra" 
add "$dir" "H"  "Quiz King of Fighters.mra" 
add "$dir" "H"  "Quiz Meitantei Neo & Geo - Quiz Daisousa Sen part 2.mra" 
add "$dir" "H"  "Rage of the Dragons.mra" 
add "$dir" "H"  "Ragnagard.mra" 
add "$dir" "H"  "Real Bout Fatal Fury (bug fix revision).mra" 
add "$dir" "H"  "Real Bout Fatal Fury 2 - The Newcomers.mra" 
add "$dir" "H"  "Real Bout Fatal Fury Special.mra" 
add "$dir" "H"  "Riding Hero.mra" 
add "$dir" "H"  "Robo Army.mra" 
add "$dir" "H"  "Samurai Shodown.mra" 
add "$dir" "H"  "Samurai Shodown II.mra" 
add "$dir" "H"  "Samurai Shodown III.mra" 
add "$dir" "H"  "Samurai Shodown IV - Amakusa's Revenge.mra" 
add "$dir" "H"  "Samurai Shodown V.mra" 
add "$dir" "H"  "Samurai Shodown V Perfect.mra" 
add "$dir" "H"  "Samurai Shodown V Special.mra" 
add "$dir" "H"  "Savage Reign.mra" 
add "$dir" "H"  "Sengoku.mra" 
add "$dir" "H"  "Sengoku 2.mra" 
add "$dir" "H"  "Sengoku 3.mra" 
add "$dir" "H"  "Shock Troopers.mra" 
add "$dir" "H"  "Shock Troopers - 2nd Squad.mra" 
add "$dir" "H"  "Shougi no Tatsujin - Master of Shougi.mra" 
add "$dir" "H"  "SNK vs. Capcom - SVC Chaos.mra" 
add "$dir" "H"  "Soccer Brawl.mra" 
add "$dir" "H"  "Spin Master.mra" 
add "$dir" "H"  "Stakes Winner.mra" 
add "$dir" "H"  "Stakes Winner 2.mra" 
add "$dir" "H"  "Street Hoop.mra" 
add "$dir" "H"  "Strikers 1945 Plus.mra" "" "STG"
add "$dir" "H"  "Super Bubble Pop.mra" 
add "$dir" "H"  "Super Dodge Ball.mra" 
add "$dir" "H"  "Super Sidekicks.mra" 
add "$dir" "H"  "Super Sidekicks 2 - The World Championship.mra" 
add "$dir" "H"  "Super Sidekicks 3 - The Next Glory.mra" 
add "$dir" "H"  "Tecmo World Soccer '96.mra" 
add "$dir" "H"  "The Eye of Typhoon - Tsunami Edition.mra" 
add "$dir" "H"  "The Irritating Maze.mra" 
add "$dir" "H"  "The King of Fighters '94.mra" 
add "$dir" "H"  "The King of Fighters '95.mra" 
add "$dir" "H"  "The King of Fighters '96.mra" 
add "$dir" "H"  "The King of Fighters '97.mra" 
add "$dir" "H"  "The King of Fighters '98 - The Slugfest.mra" 
add "$dir" "H"  "The King of Fighters '99 - Millennium Battle.mra" 
add "$dir" "H"  "The King of Fighters 2000.mra" 
add "$dir" "H"  "The King of Fighters 2001.mra" 
add "$dir" "H"  "The King of Fighters 2002.mra" 
add "$dir" "H"  "The King of Fighters 2003.mra" 
add "$dir" "H"  "The Last Blade.mra" 
add "$dir" "H"  "The Last Blade 2.mra" 
add "$dir" "H"  "The Super Spy.mra" 
add "$dir" "H"  "The Ultimate 11 - The SNK Football Championship.mra" 
add "$dir" "H"  "Thrash Rally.mra" 
add "$dir" "H"  "Top Hunter - Roddy & Cathy.mra" 
add "$dir" "H"  "Top Player's Golf.mra" 
add "$dir" "H"  "Treasure of the Caribbean.mra" 
add "$dir" "H"  "Twinkle Star Sprites.mra" 
add "$dir" "H"  "Viewpoint.mra" 
add "$dir" "H"  "Voltage Fighter - Gowcaizer.mra" 
add "$dir" "H"  "Waku Waku 7.mra" 
add "$dir" "H"  "Windjammers.mra" 
add "$dir" "H"  "World Heroes.mra" 
add "$dir" "H"  "World Heroes 2.mra" 
add "$dir" "H"  "World Heroes 2 Jet.mra" 
add "$dir" "H"  "World Heroes Perfect.mra" 
add "$dir" "H"  "Xeno Crisis.mra" 
add "$dir" "H"  "Zed Blade.mra" 
add "$dir" "H"  "Zintrick.mra" 
add "$dir" "H"  "Zupapa!.mra" 

dot

#ln -s "$AltSourceRoot/$MainDir"  "$OutputRoot/$MainDir"
